(cl:defpackage shuttles-srv
  (:use )
  (:export
   "SRVGETEMPTYSHUTTLES"
   "<SRVGETEMPTYSHUTTLES-REQUEST>"
   "SRVGETEMPTYSHUTTLES-REQUEST"
   "<SRVGETEMPTYSHUTTLES-RESPONSE>"
   "SRVGETEMPTYSHUTTLES-RESPONSE"
   "SRVGETSHUTTLESTATUS"
   "<SRVGETSHUTTLESTATUS-REQUEST>"
   "SRVGETSHUTTLESTATUS-REQUEST"
   "<SRVGETSHUTTLESTATUS-RESPONSE>"
   "SRVGETSHUTTLESTATUS-RESPONSE"
  ))

