// Generated by gencpp from file shuttles/srvGetEmptyShuttlesResponse.msg
// DO NOT EDIT!


#ifndef SHUTTLES_MESSAGE_SRVGETEMPTYSHUTTLESRESPONSE_H
#define SHUTTLES_MESSAGE_SRVGETEMPTYSHUTTLESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace shuttles
{
template <class ContainerAllocator>
struct srvGetEmptyShuttlesResponse_
{
  typedef srvGetEmptyShuttlesResponse_<ContainerAllocator> Type;

  srvGetEmptyShuttlesResponse_()
    : handles()
    , zones()  {
    }
  srvGetEmptyShuttlesResponse_(const ContainerAllocator& _alloc)
    : handles(_alloc)
    , zones(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _handles_type;
  _handles_type handles;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _zones_type;
  _zones_type zones;




  typedef boost::shared_ptr< ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srvGetEmptyShuttlesResponse_

typedef ::shuttles::srvGetEmptyShuttlesResponse_<std::allocator<void> > srvGetEmptyShuttlesResponse;

typedef boost::shared_ptr< ::shuttles::srvGetEmptyShuttlesResponse > srvGetEmptyShuttlesResponsePtr;
typedef boost::shared_ptr< ::shuttles::srvGetEmptyShuttlesResponse const> srvGetEmptyShuttlesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace shuttles

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'shuttles': ['/home/projn7cellule/PL_2018/ros_ws/src/shuttles/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af5d249f87e707b5fe578809b83b41ae";
  }

  static const char* value(const ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf5d249f87e707b5ULL;
  static const uint64_t static_value2 = 0xfe578809b83b41aeULL;
};

template<class ContainerAllocator>
struct DataType< ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shuttles/srvGetEmptyShuttlesResponse";
  }

  static const char* value(const ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] handles\n\
int32[] zones\n\
\n\
";
  }

  static const char* value(const ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.handles);
      stream.next(m.zones);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvGetEmptyShuttlesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shuttles::srvGetEmptyShuttlesResponse_<ContainerAllocator>& v)
  {
    s << indent << "handles[]" << std::endl;
    for (size_t i = 0; i < v.handles.size(); ++i)
    {
      s << indent << "  handles[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.handles[i]);
    }
    s << indent << "zones[]" << std::endl;
    for (size_t i = 0; i < v.zones.size(); ++i)
    {
      s << indent << "  zones[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.zones[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHUTTLES_MESSAGE_SRVGETEMPTYSHUTTLESRESPONSE_H
