// Generated by gencpp from file shuttles/srvGetEmptyShuttles.msg
// DO NOT EDIT!


#ifndef SHUTTLES_MESSAGE_SRVGETEMPTYSHUTTLES_H
#define SHUTTLES_MESSAGE_SRVGETEMPTYSHUTTLES_H

#include <ros/service_traits.h>


#include <shuttles/srvGetEmptyShuttlesRequest.h>
#include <shuttles/srvGetEmptyShuttlesResponse.h>


namespace shuttles
{

struct srvGetEmptyShuttles
{

typedef srvGetEmptyShuttlesRequest Request;
typedef srvGetEmptyShuttlesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvGetEmptyShuttles
} // namespace shuttles


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::shuttles::srvGetEmptyShuttles > {
  static const char* value()
  {
    return "af5d249f87e707b5fe578809b83b41ae";
  }

  static const char* value(const ::shuttles::srvGetEmptyShuttles&) { return value(); }
};

template<>
struct DataType< ::shuttles::srvGetEmptyShuttles > {
  static const char* value()
  {
    return "shuttles/srvGetEmptyShuttles";
  }

  static const char* value(const ::shuttles::srvGetEmptyShuttles&) { return value(); }
};


// service_traits::MD5Sum< ::shuttles::srvGetEmptyShuttlesRequest> should match 
// service_traits::MD5Sum< ::shuttles::srvGetEmptyShuttles > 
template<>
struct MD5Sum< ::shuttles::srvGetEmptyShuttlesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::shuttles::srvGetEmptyShuttles >::value();
  }
  static const char* value(const ::shuttles::srvGetEmptyShuttlesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::shuttles::srvGetEmptyShuttlesRequest> should match 
// service_traits::DataType< ::shuttles::srvGetEmptyShuttles > 
template<>
struct DataType< ::shuttles::srvGetEmptyShuttlesRequest>
{
  static const char* value()
  {
    return DataType< ::shuttles::srvGetEmptyShuttles >::value();
  }
  static const char* value(const ::shuttles::srvGetEmptyShuttlesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::shuttles::srvGetEmptyShuttlesResponse> should match 
// service_traits::MD5Sum< ::shuttles::srvGetEmptyShuttles > 
template<>
struct MD5Sum< ::shuttles::srvGetEmptyShuttlesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::shuttles::srvGetEmptyShuttles >::value();
  }
  static const char* value(const ::shuttles::srvGetEmptyShuttlesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::shuttles::srvGetEmptyShuttlesResponse> should match 
// service_traits::DataType< ::shuttles::srvGetEmptyShuttles > 
template<>
struct DataType< ::shuttles::srvGetEmptyShuttlesResponse>
{
  static const char* value()
  {
    return DataType< ::shuttles::srvGetEmptyShuttles >::value();
  }
  static const char* value(const ::shuttles::srvGetEmptyShuttlesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SHUTTLES_MESSAGE_SRVGETEMPTYSHUTTLES_H
