// Generated by gencpp from file shuttles/srvGetShuttleStatus.msg
// DO NOT EDIT!


#ifndef SHUTTLES_MESSAGE_SRVGETSHUTTLESTATUS_H
#define SHUTTLES_MESSAGE_SRVGETSHUTTLESTATUS_H

#include <ros/service_traits.h>


#include <shuttles/srvGetShuttleStatusRequest.h>
#include <shuttles/srvGetShuttleStatusResponse.h>


namespace shuttles
{

struct srvGetShuttleStatus
{

typedef srvGetShuttleStatusRequest Request;
typedef srvGetShuttleStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvGetShuttleStatus
} // namespace shuttles


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::shuttles::srvGetShuttleStatus > {
  static const char* value()
  {
    return "a4ce97941b4a653e0f9d7b798a04eeee";
  }

  static const char* value(const ::shuttles::srvGetShuttleStatus&) { return value(); }
};

template<>
struct DataType< ::shuttles::srvGetShuttleStatus > {
  static const char* value()
  {
    return "shuttles/srvGetShuttleStatus";
  }

  static const char* value(const ::shuttles::srvGetShuttleStatus&) { return value(); }
};


// service_traits::MD5Sum< ::shuttles::srvGetShuttleStatusRequest> should match 
// service_traits::MD5Sum< ::shuttles::srvGetShuttleStatus > 
template<>
struct MD5Sum< ::shuttles::srvGetShuttleStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::shuttles::srvGetShuttleStatus >::value();
  }
  static const char* value(const ::shuttles::srvGetShuttleStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::shuttles::srvGetShuttleStatusRequest> should match 
// service_traits::DataType< ::shuttles::srvGetShuttleStatus > 
template<>
struct DataType< ::shuttles::srvGetShuttleStatusRequest>
{
  static const char* value()
  {
    return DataType< ::shuttles::srvGetShuttleStatus >::value();
  }
  static const char* value(const ::shuttles::srvGetShuttleStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::shuttles::srvGetShuttleStatusResponse> should match 
// service_traits::MD5Sum< ::shuttles::srvGetShuttleStatus > 
template<>
struct MD5Sum< ::shuttles::srvGetShuttleStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::shuttles::srvGetShuttleStatus >::value();
  }
  static const char* value(const ::shuttles::srvGetShuttleStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::shuttles::srvGetShuttleStatusResponse> should match 
// service_traits::DataType< ::shuttles::srvGetShuttleStatus > 
template<>
struct DataType< ::shuttles::srvGetShuttleStatusResponse>
{
  static const char* value()
  {
    return DataType< ::shuttles::srvGetShuttleStatus >::value();
  }
  static const char* value(const ::shuttles::srvGetShuttleStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SHUTTLES_MESSAGE_SRVGETSHUTTLESTATUS_H
