// Generated by gencpp from file shuttles/srvGetShuttleStatusResponse.msg
// DO NOT EDIT!


#ifndef SHUTTLES_MESSAGE_SRVGETSHUTTLESTATUSRESPONSE_H
#define SHUTTLES_MESSAGE_SRVGETSHUTTLESTATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace shuttles
{
template <class ContainerAllocator>
struct srvGetShuttleStatusResponse_
{
  typedef srvGetShuttleStatusResponse_<ContainerAllocator> Type;

  srvGetShuttleStatusResponse_()
    : destination(0)
    , handlePlatform(0)
    , product(0)
    , zone(0)
    , name()  {
    }
  srvGetShuttleStatusResponse_(const ContainerAllocator& _alloc)
    : destination(0)
    , handlePlatform(0)
    , product(0)
    , zone(0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _destination_type;
  _destination_type destination;

   typedef int32_t _handlePlatform_type;
  _handlePlatform_type handlePlatform;

   typedef int32_t _product_type;
  _product_type product;

   typedef int32_t _zone_type;
  _zone_type zone;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;




  typedef boost::shared_ptr< ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srvGetShuttleStatusResponse_

typedef ::shuttles::srvGetShuttleStatusResponse_<std::allocator<void> > srvGetShuttleStatusResponse;

typedef boost::shared_ptr< ::shuttles::srvGetShuttleStatusResponse > srvGetShuttleStatusResponsePtr;
typedef boost::shared_ptr< ::shuttles::srvGetShuttleStatusResponse const> srvGetShuttleStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace shuttles

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'shuttles': ['/home/projn7cellule/PL_2018/ros_ws/src/shuttles/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58084d425adc5298b74b46f7b06eebf3";
  }

  static const char* value(const ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58084d425adc5298ULL;
  static const uint64_t static_value2 = 0xb74b46f7b06eebf3ULL;
};

template<class ContainerAllocator>
struct DataType< ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shuttles/srvGetShuttleStatusResponse";
  }

  static const char* value(const ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 destination\n\
int32 handlePlatform\n\
int32 product\n\
int32 zone\n\
string name\n\
\n\
";
  }

  static const char* value(const ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.destination);
      stream.next(m.handlePlatform);
      stream.next(m.product);
      stream.next(m.zone);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvGetShuttleStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shuttles::srvGetShuttleStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "destination: ";
    Printer<int32_t>::stream(s, indent + "  ", v.destination);
    s << indent << "handlePlatform: ";
    Printer<int32_t>::stream(s, indent + "  ", v.handlePlatform);
    s << indent << "product: ";
    Printer<int32_t>::stream(s, indent + "  ", v.product);
    s << indent << "zone: ";
    Printer<int32_t>::stream(s, indent + "  ", v.zone);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHUTTLES_MESSAGE_SRVGETSHUTTLESTATUSRESPONSE_H
