// Generated by gencpp from file shuttles/srvGetEmptyShuttlesRequest.msg
// DO NOT EDIT!


#ifndef SHUTTLES_MESSAGE_SRVGETEMPTYSHUTTLESREQUEST_H
#define SHUTTLES_MESSAGE_SRVGETEMPTYSHUTTLESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace shuttles
{
template <class ContainerAllocator>
struct srvGetEmptyShuttlesRequest_
{
  typedef srvGetEmptyShuttlesRequest_<ContainerAllocator> Type;

  srvGetEmptyShuttlesRequest_()
    {
    }
  srvGetEmptyShuttlesRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct srvGetEmptyShuttlesRequest_

typedef ::shuttles::srvGetEmptyShuttlesRequest_<std::allocator<void> > srvGetEmptyShuttlesRequest;

typedef boost::shared_ptr< ::shuttles::srvGetEmptyShuttlesRequest > srvGetEmptyShuttlesRequestPtr;
typedef boost::shared_ptr< ::shuttles::srvGetEmptyShuttlesRequest const> srvGetEmptyShuttlesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace shuttles

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'shuttles': ['/home/projn7cellule/PL_2018/ros_ws/src/shuttles/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shuttles/srvGetEmptyShuttlesRequest";
  }

  static const char* value(const ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvGetEmptyShuttlesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::shuttles::srvGetEmptyShuttlesRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SHUTTLES_MESSAGE_SRVGETEMPTYSHUTTLESREQUEST_H
